# Generated by Django 5.0 on 2023-12-16 03:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('adhar_card_number', models.CharField(max_length=16)),
                ('dob', models.DateField(default=datetime.datetime(2023, 12, 16, 3, 13, 53, 411800))),
                ('identification_marks', models.TextField()),
                ('admission_category', models.CharField(choices=[('General', 'General'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC')], max_length=50)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mail_id', models.EmailField(max_length=254)),
                ('contact_detail', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('enrollment_id', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=255)),
                ('father_qualification', models.CharField(max_length=255)),
                ('father_profession', models.CharField(max_length=255)),
                ('father_designation', models.CharField(max_length=255)),
                ('father_aadhar_card', models.CharField(max_length=16)),
                ('father_mobile_number', models.CharField(max_length=20)),
                ('father_mail_id', models.EmailField(max_length=254)),
                ('mother_name', models.CharField(max_length=255)),
                ('mother_qualification', models.CharField(max_length=255)),
                ('mother_profession', models.CharField(max_length=255)),
                ('mother_designation', models.CharField(max_length=255)),
                ('mother_aadhar_card', models.CharField(max_length=16)),
                ('mother_mobile_number', models.CharField(max_length=20)),
                ('mother_mail_id', models.EmailField(max_length=254)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_api.studentdetails')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_api.studentdetails')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('date_of_joining', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_api.studentdetails')),
            ],
        ),
    ]
