# Generated by Django 5.0 on 2023-12-16 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_api', '0002_alter_studentdetails_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='dob',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 3, 14, 34, 446713)),
        ),
    ]
