# Generated by Django 5.0 on 2023-12-16 03:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_api', '0004_alter_studentdetails_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdetails',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 3, 49, 29, 247186)),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academicdetails', to='forms_api.studentdetails'),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentupload_set', to='forms_api.studentdetails'),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='dob',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 3, 49, 29, 246409)),
        ),
    ]
