# Generated by Django 5.0 on 2023-12-16 04:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_api', '0005_alter_academicdetails_date_of_joining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdetails',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 4, 26, 19, 984283)),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_details', to='forms_api.studentdetails'),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_api.studentdetails'),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='dob',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 4, 26, 19, 983830)),
        ),
    ]
