# Generated by Django 5.0 on 2023-12-16 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_api', '0007_studentdetails_class_name_studentdetails_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 14, 44, 51, 776827)),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='class_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='dob',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 14, 44, 51, 775970)),
        ),
    ]
