# Generated by Django 5.0 on 2023-12-16 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_api', '0008_studentdetails_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='section',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='session',
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 15, 3, 16, 646740)),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='dob',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 15, 3, 16, 645953)),
        ),
    ]
